const PRODUCTS = [
    // RAÇÕES CÃO
    { id: "rc1", name: "Special Dog Carne Adulto 15kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc2", name: "Special Dog Carne Adulto 20kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc3", name: "Special Dog Carne Plus Adulto 15kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc4", name: "Special Dog Carne Plus Adulto 20kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc5", name: "Special Dog Porte Pequeno Adulto 20kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc6", name: "Special Dog Ultralife Porte Pequeno Adulto 20kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc7", name: "Special Dog Senior 15kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc8", name: "Special Dog Gold Performance Adulto 20kg", brand: "Special Dog", category: "racao-cao" },
    { id: "rc9", name: "Special Dog Bionatural Adulto Cordeiro 2,5kg", brand: "Special Dog", category: "racao-cao" },
    
    { id: "rc10", name: "Golden Special Adulto 15kg", brand: "Golden", category: "racao-cao" },
    { id: "rc11", name: "Golden Special Adulto 20kg", brand: "Golden", category: "racao-cao" },
    { id: "rc12", name: "Golden Mini Bits Frango Adulto 15kg", brand: "Golden", category: "racao-cao" },
    { id: "rc13", name: "Golden Mini Bits Carne Adulto 20kg", brand: "Golden", category: "racao-cao" },
    { id: "rc14", name: "Golden Mini Bits Filhote Frango 10kg", brand: "Golden", category: "racao-cao" },
    { id: "rc15", name: "Golden Mini Bits Salmão Adulto 3kg", brand: "Golden", category: "racao-cao" },
    { id: "rc16", name: "Golden Mini Bits Light 3kg", brand: "Golden", category: "racao-cao" },
    { id: "rc17", name: "Golden Power Training Adulto 15kg", brand: "Golden", category: "racao-cao" },
    
    { id: "rc18", name: "Premier Ambientes Internos Adulto 12kg", brand: "Premier", category: "racao-cao" },
    { id: "rc19", name: "Premier Formula Carne Adulto 15kg", brand: "Premier", category: "racao-cao" },
    { id: "rc20", name: "Premier Formula Frango Adulto 20kg", brand: "Premier", category: "racao-cao" },
    { id: "rc21", name: "Premier Formula Frango Filhote 20kg", brand: "Premier", category: "racao-cao" },
    
    { id: "rc22", name: "Finotrato Nature Adulto Raças Pequenas 15kg", brand: "Finotrato", category: "racao-cao" },
    { id: "rc23", name: "Finotrato Nature Adulto Raças Pequenas 20kg", brand: "Finotrato", category: "racao-cao" },
    { id: "rc24", name: "Finotrato Nature Adulto Raças Grandes 15kg", brand: "Finotrato", category: "racao-cao" },
    { id: "rc25", name: "Finotrato Nature Adulto Raças Grandes 20kg", brand: "Finotrato", category: "racao-cao" },
    { id: "rc26", name: "Finotrato Life Senior 15kg", brand: "Finotrato", category: "racao-cao" },
    
    { id: "rc27", name: "Origens Class 15kg", brand: "Origens", category: "racao-cao" },
    { id: "rc28", name: "Fresh Meat Frango Filhote 2,5kg", brand: "Fresh Meat", category: "racao-cao" },
    { id: "rc29", name: "Fresh Meat Frango Adulto 2,5kg", brand: "Fresh Meat", category: "racao-cao" },

    // RAÇÕES GATO
    { id: "rg1", name: "Golden Frango Filhote 10,1kg", brand: "Golden", category: "racao-gato" },
    { id: "rg2", name: "Golden Frango Adulto 10,1kg", brand: "Golden", category: "racao-gato" },
    { id: "rg3", name: "Golden Carne Adulto 10,1kg", brand: "Golden", category: "racao-gato" },
    { id: "rg4", name: "Golden Castrados Salmão 10,1kg", brand: "Golden", category: "racao-gato" },
    { id: "rg5", name: "Golden Castrados Frango 10,1kg", brand: "Golden", category: "racao-gato" },
    { id: "rg6", name: "Golden Castrados Salmão 3kg", brand: "Golden", category: "racao-gato" },

    // PETISCOS/SACHÊS (Cookies, Biscoitos, Palitos, Sachês Cão/Gato)
    { id: "pt1", name: "Cookie Premier Original Cão 250g", brand: "Premier", category: "petisco-sache" },
    { id: "pt2", name: "Cookie Premier Coco Cão 250g", brand: "Premier", category: "petisco-sache" },
    { id: "pt3", name: "Cookie Premier Frutas Vermelhas Cão 250g", brand: "Premier", category: "petisco-sache" },
    { id: "pt4", name: "Cookie Golden Original Cão 350g", brand: "Golden", category: "petisco-sache" },
    { id: "pt5", name: "Cookie Special Dog Ultralife Minions Cão 250g", brand: "Special Dog", category: "petisco-sache" },
    { id: "pt6", name: "Cookie Special Dog Ultralife Frutas Vermelhas Cão 250g", brand: "Special Dog", category: "petisco-sache" },
    { id: "pt7", name: "Cookie Fresh Meat Cordeiro Cão 150g", brand: "Fresh Meat", category: "petisco-sache" },
    { id: "pt8", name: "Cookie Fresh Meat Frango Cão 150g", brand: "Fresh Meat", category: "petisco-sache" },
    { id: "pt9", name: "Cookie Fórmula Natural Pele/Pelagem Cão 120g", brand: "Fórmula Natural", category: "petisco-sache" },
    { id: "pt10", name: "Cookie Fórmula Natural Antiestresse Cão 120g", brand: "Fórmula Natural", category: "petisco-sache" },
    { id: "pt11", name: "Doogs Palito Cão 1kg", brand: "Doogs", category: "petisco-sache" },
    { id: "pt12", name: "Doogs Palito Maracujá Cão 50g", brand: "Doogs", category: "petisco-sache" },
    { id: "pt13", name: "Doogs Palito Maçã com Canela Cão 50g", brand: "Doogs", category: "petisco-sache" },
    { id: "pt14", name: "Doogs Palito Menta Cão 50g", brand: "Doogs", category: "petisco-sache" },
    { id: "pt15", name: "Orelha Bovina (Unidade)", brand: "Outros", category: "petisco-sache" },
    { id: "pt16", name: "Orelha Suína (Unidade)", brand: "Outros", category: "petisco-sache" },
    { id: "pt17", name: "Chifre Bovino (Unidade)", brand: "Outros", category: "petisco-sache" },
    { id: "pt18", name: "Weegs Wow Petisco Cão", brand: "Weegs", category: "petisco-sache" },
    { id: "pt19", name: "Weegs Wow Petisco Gato", brand: "Weegs", category: "petisco-sache" },
    { id: "pt20", name: "Pipoca Wow Pet 30g", brand: "Outros", category: "petisco-sache" },
    
    { id: "pt21", name: "Sachê Special Dog Ultralife Cão", brand: "Special Dog", category: "petisco-sache" },
    { id: "pt22", name: "Sachê Pedigree Cão", brand: "Pedigree", category: "petisco-sache" },
    { id: "pt23", name: "Sachê Golden Gourmet Cão", brand: "Golden", category: "petisco-sache" },
    { id: "pt24", name: "Sachê Gran Plus Cão", brand: "Gran Plus", category: "petisco-sache" },
    
    { id: "pt25", name: "Sachê Special Cat Ultralife Gato", brand: "Special Cat", category: "petisco-sache" },
    { id: "pt26", name: "Sachê Golden Gourmet Gato", brand: "Golden", category: "petisco-sache" },
    { id: "pt27", name: "Sachê Gran Plus Gato", brand: "Gran Plus", category: "petisco-sache" },
    { id: "pt28", name: "Sachê Whiskas Gato", brand: "Whiskas", category: "petisco-sache" },
    { id: "pt29", name: "Sachê Optimum Gato", brand: "Optimum", category: "petisco-sache" },
    { id: "pt30", name: "Sachê Churu Gato", brand: "Churu", category: "petisco-sache" },

    // RAÇÕES A GRANEL
    { id: "gr1", name: "Premier Fórmula Carne Adulto (Granel)", brand: "Premier", category: "granel" },
    { id: "gr2", name: "Premier Fórmula Frango Filhote (Granel)", brand: "Premier", category: "granel" },
    { id: "gr3", name: "Premier Fórmula Frango Adulto (Granel)", brand: "Premier", category: "granel" },
    { id: "gr4", name: "Premier Ambientes Internos Adulto (Granel)", brand: "Premier", category: "granel" },
    { id: "gr5", name: "Special Dog Junior (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr6", name: "Special Dog Porte Pequeno Adulto (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr7", name: "Special Dog Porte Pequeno Adulto Ultralife (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr8", name: "Special Dog Plus Adulto (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr9", name: "Special Dog Gold Performance Adulto (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr10", name: "Special Dog Senior (Granel)", brand: "Special Dog", category: "granel" },
    { id: "gr11", name: "Golden Mini Bits Filhote Frango (Granel)", brand: "Golden", category: "granel" },
    { id: "gr12", name: "Golden Mini Bits Adulto Frango (Granel)", brand: "Golden", category: "granel" },
    { id: "gr13", name: "Finotrato Nature Raças Pequenas Adulto (Granel)", brand: "Finotrato", category: "granel" },
    { id: "gr14", name: "Finotrato Senior (Granel)", brand: "Finotrato", category: "granel" },
    { id: "gr15", name: "Origens Class (Granel)", brand: "Origens", category: "granel" },
    { id: "gr16", name: "N&D Cordeiro (Granel)", brand: "N&D", category: "granel" },
    { id: "gr17", name: "Golden Filhote Frango Gato (Granel)", brand: "Golden", category: "granel" },
    { id: "gr18", name: "Golden Adulto Frango Gato (Granel)", brand: "Golden", category: "granel" },
    { id: "gr19", name: "Golden Castrado Salmão Gato (Granel)", brand: "Golden", category: "granel" },
    { id: "gr20", name: "Golden Castrado Frango Gato (Granel)", brand: "Golden", category: "granel" },
    { id: "gr21", name: "Special Cat Filhote Gato (Granel)", brand: "Special Cat", category: "granel" },
    { id: "gr22", name: "Special Cat Adulto Carne Gato (Granel)", brand: "Special Cat", category: "granel" },
    { id: "gr23", name: "Special Cat Castrado Gato (Granel)", brand: "Special Cat", category: "granel" },

    // TAPETES / AREIAS
    { id: "at1", name: "Tapete Higiênico Doghood Branco 80x60 (c/ 30 un)", brand: "Doghood", category: "areia-tapete" },
    { id: "at2", name: "Tapete Higiênico Doghood Carvão Ativado 80x60 (c/ 30 un)", brand: "Doghood", category: "areia-tapete" },
    { id: "at3", name: "Tapete Higiênico Zeepad Branco 80x60 (c/ 30 un)", brand: "Zeepad", category: "areia-tapete" },
    { id: "at4", name: "Tapete Higiênico Pé de Cão Branco 60x60 (c/ 30 un)", brand: "Pé de Cão", category: "areia-tapete" },
    { id: "at5", name: "Tapete Higiênico Doghood Branco 80x60 (Avulso)", brand: "Doghood", category: "areia-tapete" },
    { id: "at6", name: "Tapete Higiênico Doghood Carvão Ativado 80x60 (Avulso)", brand: "Doghood", category: "areia-tapete" },
    { id: "at7", name: "Areia Sanitária Xô Cheiro 8kg", brand: "Xô Cheiro", category: "areia-tapete" },
    { id: "at8", name: "Areia Sanitária Pipicat Classic 4kg", brand: "Pipicat", category: "areia-tapete" },
    { id: "at9", name: "Areia Sanitária Pipicat Campestre 4kg", brand: "Pipicat", category: "areia-tapete" },
    { id: "at10", name: "Areia Sanitária Pipicat Floral 4kg", brand: "Pipicat", category: "areia-tapete" },
    { id: "at11", name: "Aditivo Antiodor Pipicat Campestre 500g", brand: "Pipicat", category: "areia-tapete" },
    { id: "at12", name: "Areia Sanitária Xcat Carbon 3kg", brand: "Xcat", category: "areia-tapete" },
    { id: "at13", name: "Areia Sanitária Xcat Biogolden Mandioca 4kg", brand: "Xcat", category: "areia-tapete" },
    { id: "at14", name: "Granulado Higiênico Progato Branco 1,8kg", brand: "Progato", category: "areia-tapete" },

    // MEDICAMENTOS
    { id: "md1", name: "Antipulgas Simparic 1,3-2,5kg", brand: "Simparic", category: "medicamento" },
    { id: "md2", name: "Antipulgas Simparic 2,6-5kg", brand: "Simparic", category: "medicamento" },
    { id: "md3", name: "Antipulgas Simparic 5,1-10kg", brand: "Simparic", category: "medicamento" },
    { id: "md4", name: "Antipulgas Simparic 10,1-20kg", brand: "Simparic", category: "medicamento" },
    { id: "md5", name: "Antipulgas Simparic 20,1-40kg", brand: "Simparic", category: "medicamento" },
    { id: "md6", name: "Antipulgas Nexgard 2-4kg", brand: "Nexgard", category: "medicamento" },
    { id: "md7", name: "Coleira Antipulgas Seresto Até 8kg", brand: "Seresto", category: "medicamento" },
    { id: "md8", name: "Vermífugo Endogard 10kg", brand: "Endogard", category: "medicamento" },
    { id: "md9", name: "Vermífugo Top Dog 10kg", brand: "Top Dog", category: "medicamento" },
    { id: "md10", name: "Prediderm 20mg (Anti-inflamatório)", brand: "Prediderm", category: "medicamento" },
    { id: "md11", name: "Antiparasitário Banni3 Pipeta Gato 2,5kg", brand: "Banni3", category: "medicamento" },
    { id: "md12", name: "Antiparasitário Banni3 Pipeta Gato 2,6-7,5kg", brand: "Banni3", category: "medicamento" },
    { id: "md13", name: "Raticida Granulado", brand: "Outros", category: "medicamento" },
    { id: "md14", name: "Raticida Cola Rato", brand: "Outros", category: "medicamento" },

    // ACESSÓRIOS & BRINQUEDOS & HIGIENE (Cão e Gato e Pássaros)
    { id: "ac1", name: "Camas Pet (Modelos e Tamanhos Variados)", brand: "Variados", category: "acessorio" },
    { id: "ac2", name: "Roupas Pet (Modelos e Tamanhos Variados)", brand: "Variados", category: "acessorio" },
    { id: "ac3", name: "Guia / Peitoral / Coleira (Modelos e Tamanhos Variados)", brand: "Variados", category: "acessorio" },
    { id: "ac4", name: "Boné Pet", brand: "Outros", category: "acessorio" },
    { id: "ac5", name: "Meia Pet", brand: "Outros", category: "acessorio" },
    { id: "ac6", name: "Bolinha de Vinil", brand: "Brinquedos", category: "acessorio" },
    { id: "ac7", name: "Bolinha Maciça", brand: "Brinquedos", category: "acessorio" },
    { id: "ac8", name: "Bolinha de Tênis Pet", brand: "Brinquedos", category: "acessorio" },
    { id: "ac9", name: "Mordedor Pneu Maciço", brand: "Brinquedos", category: "acessorio" },
    { id: "ac10", name: "Mordedor de Vinil", brand: "Brinquedos", category: "acessorio" },
    { id: "ac11", name: "Mordedor de Corda", brand: "Brinquedos", category: "acessorio" },
    { id: "ac12", name: "Brinquedos de Corda Variados", brand: "Brinquedos", category: "acessorio" },
    { id: "ac13", name: "Pelúcia Polvo", brand: "Brinquedos", category: "acessorio" },
    { id: "ac14", name: "Pelúcia Urso", brand: "Brinquedos", category: "acessorio" },
    { id: "ac15", name: "Galinha de Borracha", brand: "Brinquedos", category: "acessorio" },
    { id: "ac16", name: "Bolinha com Guizo Gato", brand: "Brinquedos", category: "acessorio" },
    { id: "ac17", name: "Varinhas com Penas Gato", brand: "Brinquedos", category: "acessorio" },
    { id: "ac18", name: "Arranhador de Canto de Sofá Gato", brand: "Brinquedos", category: "acessorio" },
    { id: "ac19", name: "Brinquedo Gato com Chocalho", brand: "Brinquedos", category: "acessorio" },
    { id: "ac20", name: "Coleira de Pescoço Gato", brand: "Outros", category: "acessorio" },
    { id: "ac21", name: "Focinheira (Tamanhos Variados)", brand: "Outros", category: "acessorio" },
    { id: "ac22", name: "Colar Elizabetano (Tamanhos Variados)", brand: "Outros", category: "acessorio" },
    { id: "ac23", name: "Kit Dispenser Cata Caca com Refil", brand: "Outros", category: "acessorio" },
    { id: "ac24", name: "Refil Cata Caca Avulso", brand: "Outros", category: "acessorio" },
    
    { id: "hy1", name: "Shampoo Melancia 500ml", brand: "Higiene", category: "acessorio" },
    { id: "hy2", name: "Shampoo Tutti Frutti 500ml", brand: "Higiene", category: "acessorio" },
    { id: "hy3", name: "Shampoo Clorexidina 500ml (Antisséptico)", brand: "Higiene", category: "acessorio" },
    { id: "hy4", name: "Shampoo Antipulgas 500ml", brand: "Higiene", category: "acessorio" },
    { id: "hy5", name: "Shampoo Allermyl Virbac 500ml (Dermatológico)", brand: "Virbac", category: "acessorio" },
    { id: "hy6", name: "Banho a Seco Pet Clean 500ml", brand: "Pet Clean", category: "acessorio" },
    { id: "hy7", name: "Sabonete Matacura 80g", brand: "Matacura", category: "acessorio" },
    { id: "hy8", name: "Spray Bucal Malvapet 60ml", brand: "Malvapet", category: "acessorio" },
    { id: "hy9", name: "Escova de Dente Pet Avulsa", brand: "Higiene", category: "acessorio" },
    
    { id: "cm1", name: "Comedouro Alto Ergonômico Gato", brand: "Utensílios", category: "acessorio" },
    { id: "cm2", name: "Comedouro Pesado Alumínio Cão", brand: "Utensílios", category: "acessorio" },
    { id: "cm3", name: "Comedouro Dupla Função", brand: "Utensílios", category: "acessorio" },
    { id: "cm4", name: "Comedouro Foodtimer (Comedouro Lento)", brand: "Utensílios", category: "acessorio" },
    { id: "cm5", name: "Comedouro Duplo", brand: "Utensílios", category: "acessorio" },
    { id: "cm6", name: "Bandeja Higiênica Gato", brand: "Utensílios", category: "acessorio" },
    { id: "cm7", name: "Pá Higiênica Gato", brand: "Utensílios", category: "acessorio" },
    
    { id: "ps1", name: "Comedouro para Pássaro", brand: "Pássaros", category: "acessorio" },
    { id: "ps2", name: "Bebedouro para Pássaro", brand: "Pássaros", category: "acessorio" },
    { id: "ps3", name: "Bloco de Cálcio para Pássaro", brand: "Pássaros", category: "acessorio" }
];
